version: '3'

services:
  # Angular App
  angular-app:
    container_name: angular-app
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run client:dev:docker
    ports:
      - 4201:4200

  # Nest App
  api:
    container_name: nest-app
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: yarn api:dev:docker
    ports:
      - 4310:3333 # API Entry port
      - 4311:4311 # Server Debugging port

volumes:
  mono-node-modules: null
