version: '3'

services:
  # Nest App
  api:
    container_name: nest-app
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: yarn api:dev:docker
    ports:
      - 4310:3333 # API Entry port
      - 4311:4311 # Server Debugging port

volumes:
  mono-node-modules: null
